buildscript {
    ext.kotlin_version = '2.4.10'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.2'
        // AGP 9 brings its own Kotlin plugin. This line only bumps KGP past
        // the version AGP ships with. Don't apply kotlin.android on top.
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'com.autonomousapps.dependency-analysis' version '3.18.0'
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
    }
}