plugins {
    alias libs.plugins.android.library
    alias libs.plugins.dependency.analysis
}

android {
    namespace 'adrianogba.stario.launcher.hidden'
    compileSdk 37
    compileSdkMinor 1

    defaultConfig {
        minSdkVersion 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    compileOnly libs.refine.annotation
    annotationProcessor libs.refine.annotation.processor
}