plugins {
    alias libs.plugins.android.application
    alias libs.plugins.dependency.analysis
    alias libs.plugins.refine
    alias libs.plugins.compose.compiler
}

def hasSigningConfig = ['keystorePath', 'keystorePassword', 'keyAlias', 'keyPassword']
        .every { project.hasProperty(it) }

android {
    namespace 'adrianogba.stario.launcher'
    compileSdk 37
    compileSdkMinor 1

    defaultConfig {
        applicationId 'adrianogba.stario.launcher'
        minSdkVersion 33
        targetSdkVersion 37
        versionCode 97
        versionName '2.16'
    }

    signingConfigs {
        release {
            if (hasSigningConfig) {
                storeFile file(project.getProperty('keystorePath'))
                storePassword project.getProperty('keystorePassword')
                keyAlias project.getProperty('keyAlias')
                keyPassword project.getProperty('keyPassword')
            }
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), "proguard-rules.txt"
            if (hasSigningConfig) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            debuggable true
            applicationIdSuffix ".debug"
        }
    }

    sourceSets {
        main {
            res {
                srcDirs = ['src/main/res/common',
                           'src/main/res/themes',
                           'src/main/res/pins',
                           'src/main/res/applications',
                           'src/main/res/strings',
                           'src/main/res/extract',
                           'src/main/res/launcher',
                           'src/main/res/drawer',
                           'src/main/res/drawer_interactions',
                           'src/main/res/page_manager',
                           'src/main/res/page_manager_dialogs',
                           'src/main/res/briefing',
                           'src/main/res/settings',
                           'src/main/res/settings_dialogs',
                           'src/main/res/search',
                           'src/main/res/scroller',
                           'src/main/res/sheet',
                           'src/main/res/splash',
                           'src/main/res/notes',
                           'src/main/res/editor',
                           'src/main/res/interactions',
                           'src/main/res/home',
                           'src/main/res/widgets',
                           'src/main/res/media',
                           'src/main/res/weather',
                           'src/main/res/glance',
                           'src/main/res/calendar']
            }
        }
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    lint {
        disable 'MissingTranslation'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
        }
    }

    afterEvaluate {
        def versionName = android.defaultConfig.versionName

        tasks.register("getVersionName") {
            doLast {
                println versionName
            }
        }
    }
}

dependencies {
    implementation project(':hidden')

    // Transitive dependencies
    implementation libs.androidx.activity
    implementation libs.androidx.annotation
    implementation libs.androidx.appcompat
    implementation libs.androidx.appcompat.resources
    implementation libs.androidx.asynclayoutinflater
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.coordinatorlayout
    implementation libs.androidx.core
    implementation libs.androidx.customview
    implementation libs.androidx.dynamicanimation
    implementation libs.androidx.fragment
    implementation libs.androidx.interpolator
    implementation libs.androidx.lifecycle.common
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.localbroadcastmanager
    implementation libs.androidx.palette
    implementation libs.androidx.recyclerview
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.transition
    implementation libs.androidx.viewpager

    implementation libs.compose.animation.core
    implementation libs.compose.foundation
    implementation libs.compose.runtime
    implementation libs.compose.ui
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui.unit
    implementation libs.compose.material3
    implementation libs.backdrop

    implementation libs.google.material
    implementation libs.google.flexbox
    implementation libs.carbon
    implementation libs.squigglyslider
    implementation libs.smarttablayout

    implementation libs.gson
    implementation libs.jsoup
    implementation libs.okhttp
    implementation libs.glide
    implementation libs.glide.transformations
    implementation libs.kotlinx.coroutines.core
    implementation libs.jetbrains.annotations
    implementation libs.rssparser

    // Hidden APIs
    implementation libs.refine.runtime
    implementation libs.restriction.bypass

    implementation libs.sunrise.sunset
    implementation(libs.dateparser) {
        exclude group: 'org.projectlombok'
    }

    annotationProcessor libs.androidx.annotation

    testImplementation libs.junit
}
